version: '3.5'

services:
    openvas:
        image: cirne/openvas-light
        container_name: openvas
        volumes:
            - plugindata:/usr/local/var/lib/openvas/plugins
            - ./gvm:/usr/var/lib/gvm
    
volumes:
  plugindata:
    driver: local
