version: '3.5'

services:
    openvas:
        image: cirne/openvas-light
        build: 
          context: .
          args: 
            OPENVAS_VERSION: 7.0.0
            VERSION: 1.0
            GVM_LIBS_VERSION: 11.0.0
        container_name: openvas
        volumes:
            - plugindata:/usr/local/var/lib/openvas/plugins
            - ./gvm:/usr/var/lib/gvm
    
volumes:
  plugindata:
    driver: local
